# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d3f366f5fa4ab867c4f56a79aab58723dc9772eaad4201dc311d0b7e87820cb8eafe971f05550d2ebdd85252b0c201f0e0b523f3ec0fc77f21fe10f39c2c8d8

test:
  secret_key_base: 4608815ff0981d46c3833a464ee3ef45c9543c22c49e574d284161cb208021d61c36f71c943e5dd90da8045472d7fce88a773dea2b5c9d455196d33ac8f9dec7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
